DCES-667: Added new endpoints to get FDC and Concor contributions for a given set of IDs.
ministryofjustice/laa-maat-court-data-api pull request #1080
Opened 2024-12-09 17:15 UTC by vvartakMoJ

## What

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-667)

Added 2 new endpoints viz /debt-collection-enforcement/fdc-contributions and /debt-collection-enforcement/concor-contribution-xml to get the FDC and Concor contributions data for a given list of IDs.

Found and fixed an issue whereby some fields (e.g. STATUS, JUD_APPORTION_PERCENT etc), were not mapped and hence not returned by the endpoint /debt-collection-enforcement/fdc-contribution-files.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

## Additional checks

- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.

2024-12-09 17:16 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
> -    private static final Function<FdcContributionsEntity, FdcContributionEntry> BUILD_FDC_ENTRY =
This method is missing some fields like judApportionPercent, status etc which were always being returned as null. There is already a suitable mapper for this which does a better job and should be used instead.

2024-12-10 16:49 UTC, Mhowell494 requested changes

2024-12-11 10:25 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
> +    @StandardApiResponseCodes
I'm not quite sure what is needed here, but happy to create a separate JIRA to look at all these things in one go as tech debt. Need to get this functionality out urgently as it's blocking other development.

2024-12-11 10:25 UTC, vvartakMoJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java
> +    void testGetConcorContributionXmlWhenNotFound() {
Will add to the tech debt ticket to resolve separately.

2024-12-11 10:26 UTC, vvartakMoJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
> +        assertEquals(expectedValue.getId(), responseValue.getId());
Will add to the tech debt ticket to resolve separately.

2024-12-11 10:41 UTC, vvartakMoJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestControllerTest.java
> +                .content("[]"))
Test added

2024-12-11 10:41 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
>          return concorFileList.stream().map(cc -> ConcorContributionResponse.builder()
Done.

2024-12-11 10:41 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
> +        List<ConcorContributionsEntity> concorFileList = concorRepository.findByIdIn(new HashSet(idList));
Done

2024-12-11 10:42 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/ConcorContributionsService.java
> +    private static List<ConcorContributionResponse> getConcorContributionResponses(
Good suggestion, done.

2024-12-11 10:42 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
> +    private FdcContributionsResponse getFdcContributionsResponse(Supplier<List<FdcContributionsEntity>> repositoryCall) {
Good suggestion, done.

2024-12-11 10:42 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/FdcContributionsController.java
> +    }
Good suggestion, done.

2024-12-11 10:42 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/service/FdcContributionsService.java
>          return FdcContributionsResponse.builder().fdcContributions(fdcContributionEntries).build();
Done

2024-12-11 10:56 UTC, vvartakMoJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/ConcorContributionsServiceTest.java
> +    void testGetConcorContributionXmlWhenNotFound() {
JIRA ticket created to handle this: https://dsdmoj.atlassian.net/browse/DCES-670

2024-12-11 10:56 UTC, vvartakMoJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/FdcContributionsServiceTest.java
> +        assertEquals(expectedValue.getId(), responseValue.getId());
JIRA ticket created: https://dsdmoj.atlassian.net/browse/DCES-670

2024-12-11 10:56 UTC, vvartakMoJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/dces/controller/ConcorContributionsRestController.java
> +    @StandardApiResponseCodes
JIRA ticket created: https://dsdmoj.atlassian.net/browse/DCES-670

2024-12-11 17:48 UTC, Mhowell494 approved these changes
Thank you for addressing some of the issues in this PR—it’s a good step forward. I’d like to see the remaining concerns resolved, particularly those related to the Swagger documentation, as this is quite important. If possible, please prioritise these fixes in a follow-up. That said, given the time constraints, I’m happy for this to be merged for now.

2024-12-12 09:33 UTC, merged