removed the sqs listener. There are error code 400 type errors for sq…
ministryofjustice/laa-maat-court-data-api pull request #328
Opened 2021-08-17 15:37 UTC by atharmajeed

…s not found.

## What

[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)

Describe what you did and why.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2021-08-17 16:38 UTC, laurentqro approved these changes

2021-08-17 20:51 UTC, msahilan07 requested changes
This is the wrong listener.  We shouldn't be removing this. I guess we should be removing LaaStatusJobListener. Let's have a call.

2021-08-18 08:01 UTC, nyenugulamoj approved these changes

2021-08-18 08:02 UTC, nyenugulamoj approved these changes

2021-08-18 11:42 UTC, msahilan07 approved these changes

2021-08-18 14:49 UTC, merged