LCAM-286|Add Entity and Repository classes for Contributions
ministryofjustice/laa-maat-court-data-api pull request #612
Opened 2022-10-31 12:44 UTC by venkat980

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-286)

Add Entity and Repository classes for Contributions.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2022-11-01 09:41 UTC, muthusubra reviewed
What about Impl and Service classes?

2022-11-01 09:50 UTC, venkat980 commented
> What about Impl and Service classes?

it was decided that we will only create the Entity and Repository classes for now, same as LCAM-287.

2022-11-01 12:28 UTC, Mhowell494 requested changes

2022-11-01 12:28 UTC, Mhowell494 commented on maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
> +    @Column(name = "CONTRIBUTION_CAP", nullable = false)
This looks like a monetary value, so I think BigDecimal is more appropriate.

2022-11-01 12:28 UTC, Mhowell494 commented on maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
> +    private Integer monthlyContributions;
This looks like a monetary value, so I think BigDecimal is more appropriate.

2022-11-01 12:28 UTC, Mhowell494 commented on maat-court-data-api/src/main/java/gov/uk/courtdata/entity/ContributionsEntity.java
> +    private Integer upfrontContributions;
This looks like a monetary value, so I think BigDecimal is more appropriate.

2022-11-03 11:19 UTC, Mhowell494 approved these changes

2022-11-03 11:19 UTC, merged