WIP: Add Endpoints for Contributions Table
ministryofjustice/laa-maat-court-data-api pull request #714
Opened 2023-04-18 14:00 UTC by nigelpain

## What

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-375)

Added three new endpoints to the application to perform operations against the contributions table based on those specified in the calc_appeal_contrib stored procedure:
- *find* Take a repId, and uses this to query the contributions table for any current matching rows (that is those where the active column has a value of'Y'). If no row is found then a 404 response is returned.
- *update* Takes the json passed through in the request body and performs validation against it according to DB constraints. It then queries the contributions table to find the matching row to update, if no row is found returns a 404 response. Otherwise maps the updated values from the request body to the entity and saves them to the database.
- *create* Takes json passed through in the request body and performs validation against it according to DB constraints. Then queries the contributions table to see if there is an existing row. If there is it updates this row to be the 'old' row by setting the replaced date, active to 'Y' and latest to 'N'. Then the request data is mapped to an entity before saving it to the database.

## TODO
- Write integration tests for ContributionsController.
- Get PR reviewed and action any comments.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2023-05-03 10:25 UTC, AafAnsari commented
- `contributions` package is not required as we already have `contribution` package.
- `ContributionsImpl` is not required and the repository calls can be made from the service class itself
- Test methods to follow given_when_then format for all test cases
- For all tests it’s best to use the actual values instead of generic any() where the test is relying on specific value and not any().

2023-05-03 10:25 UTC, AafAnsari requested changes

2023-05-03 10:25 UTC, AafAnsari commented on maat-court-data-api/src/test/java/gov/uk/courtdata/contributions/service/ContributionsServiceTest.java
> +    }
mock calls for `contributionsImpl.find()` and `contributionsMapper.mapEntityToDTO` can be verified. Same goes for all test cases where mock is used

2023-05-03 10:25 UTC, AafAnsari commented on maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContributionsRepository.java
> +
method can be renamed to `updateExistingContributionToInactive`

2023-05-03 10:25 UTC, AafAnsari commented on maat-court-data-api/src/main/java/gov/uk/courtdata/repository/ContributionsRepository.java
>  }
method can be renamed to `updateExistingContributionToPrior`

2023-05-03 10:25 UTC, AafAnsari commented on maat-court-data-api/src/main/java/gov/uk/courtdata/contributions/impl/ContributionsImpl.java
> +    public Optional<Void> updateInactiveAndPrior(Integer repId, LocalDate effectiveDate) {
method can be renamed to `updateExistingContributions`

2023-05-03 10:53 UTC, AafAnsari requested changes

2023-05-03 10:53 UTC, AafAnsari commented on maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contributions/ContributionsControllerIntegrationTest.java
> +                      @Autowired ContributionsRepository contributionsRepository) {
`setUP` typo

2023-05-03 10:53 UTC, AafAnsari commented on maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contributions/ContributionsControllerIntegrationTest.java
> +
newline can be removed

2023-05-03 16:24 UTC, loganathanMOJ commented on maat-court-data-api/src/main/java/gov/uk/courtdata/contributions/controller/ContributionsController.java
> +    public ResponseEntity<ContributionsDTO> update(@Valid @RequestBody UpdateContributions updateContributions) {
This need for schema validation (eg @NotNull)

2023-05-03 16:25 UTC, loganathanMOJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/contributions/impl/ContributionsImplTest.java
> +
Fixed now

2023-05-03 16:25 UTC, loganathanMOJ commented on maat-court-data-api/src/test/java/gov/uk/courtdata/integration/contributions/ContributionsControllerIntegrationTest.java
> +                      @Autowired ContributionsRepository contributionsRepository) {
Thanks. fixed now

2023-05-05 16:13 UTC, stone-dj requested changes

2023-05-05 16:13 UTC, stone-dj commented on maat-court-data-api/src/main/java/gov/uk/courtdata/model/contributions/Contributions.java
> +package gov.uk.courtdata.model.contributions;
I understand this is still WIP, I'm not sure if the package structure is quite right for some of the classes. Specifically I would expect classes which are only used within a specific functional domain to sit inside a sub-package of that same domain.

i.e. If the Contributions model class is only used by classes in the package `gov.uk.courtdata.contribution` (and it's sub-packages), I would expect the `Contributions` class to sit in the package  `gov.uk.courtdata.contribution.model`

This is consistent with the majority of the existing code and is IMHO a good structure as it allows us to more easily determine the scope of usages of a given class. Also it should reduce package-tangle and ensure dependancies flow vertically in a single direction (minimising inter-package dependancies).

Am more than happy to have a discussion on this and go into more detail when you're next online and take on board any downsides to this approach I may have missed.

https://stackoverflow.com/questions/15321702/what-does-package-tangle-index-data-indicate-in-sonar

2023-05-09 11:11 UTC, AafAnsari approved these changes

2023-05-09 12:18 UTC, stone-dj commented
There does not appear to be an agreed upon and documented standard package structure, this is to be discussed and decided on outside of this Pull Request.

2023-05-09 12:18 UTC, stone-dj commented
There does not appear to be an agreed upon and documented standard package structure, this is to be discussed and decided on outside of this Pull Request.

2023-05-09 12:20 UTC, stone-dj commented
There does not appear to be an agreed upon and documented standard package structure, this is to be discussed and decided on outside of this Pull Request.

2023-05-09 12:56 UTC, merged