DCES-193 FDC Global Update
ministryofjustice/laa-maat-court-data-api pull request #927
Opened 2024-02-08 10:04 UTC by LAA-Dave-Edwards

## What

[Link to story](https://dsdmoj.atlassian.net/browse/DCES-193)

Adding endpoint to be used in the modernised maat-5 job, the "global update" to prime fdc entries for sending to the debt recovery company.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2024-02-08 12:05 UTC, stone-dj requested changes
Have left some review feedback, please take a look and let me know

2024-02-09 10:29 UTC, LAA-Dave-Edwards commented on maat-court-data-api/src/main/java/gov/uk/courtdata/repository/FdcContributionsRepository.java
> +    @Query(nativeQuery = true, value = "MERGE into TOGDATA.fdc_contributions fc " +
This is very handy! Thanks for the info on this :)

2024-02-09 11:28 UTC, LAA-Dave-Edwards commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionRepositoryTest.java
> +    byte[] getCaptorHash(){
I had a think on this, and I'm not sure of the benefit. The int[] isn't too readable in the final static, but neither would a string.
I would argue a {1,-24,-114,53} is just as readable as "a1fc92", not usefully so being my reading. And a change in either would require a computer to notice 100% of the time. 
E.g. aaa213561322231acf -> aaa213561322331acf
Is already painful to notice.

2024-02-09 13:51 UTC, stone-dj commented on maat-court-data-api/src/test/java/gov/uk/courtdata/dces/service/DebtCollectionRepositoryTest.java
> +    byte[] getCaptorHash(){
Sure, you make a fair point, no requirement to change it.

2024-02-09 14:32 UTC, stone-dj approved these changes
Changes look good

2024-02-09 14:46 UTC, merged